version: '3.8'
services:
  db:
    image: postgres
    container_name: filesync-db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=filesync
  filesync:
    container_name: filesync
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgres://postgres:postgres@filesync-db/filesync?sslmode=disable"
    ports:
      - "8081:8081"
    volumes:
      - ./:/app
    depends_on:
      - db